// SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity 0.8.24;

enum ContractVersion {
    Unspecified,
    ERC20,
    InternalToken,
    MasterPoolRegistry,
    Governance,
    MasterPool,
    AuthRegistry,
    FeederPool,
    FeederVault,
    FeederPoolRegistry,
    ReceivableRegistry,
    MasterLiquidator,
    Receivable,
    BorrowerAccountFactory,
    BorrowerAccount,
    MasterTreasuryRegistry,
    CompanyAccountV1,
    TradeRegistry,
    MasterTreasury,
    ExchangePool,
    Governor,
    CompanyAccountFactory,
    OnTradeExchangeV2,
    OffTradeExchangeV2,
    SegregatedTreasury,
    SatoshiTest,
    MultiSig,
    CompanyAccount,
    OnTradeExchange,
    OffTradeExchange
}
